/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "C-ITS.ASN"
 */

#ifndef	_Lane_H_
#define	_Lane_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LaneID.h"
#include "LaneAttributes.h"
#include "AllowedManeuvers.h"
#include "PointList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ConnectsToList;

/* Lane */
typedef struct Lane {
	LaneID_t	 laneID;
	LaneAttributes_t	 laneAttributes;
	AllowedManeuvers_t	*maneuvers	/* OPTIONAL */;
	struct ConnectsToList	*connectsTo	/* OPTIONAL */;
	PointList_t	 points;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Lane_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Lane;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ConnectsToList.h"

#endif	/* _Lane_H_ */
#include <asn_internal.h>
