/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "C-ITS.ASN"
 */

#ifndef	_PointAttributeSet_H_
#define	_PointAttributeSet_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PointAttributeSet */
typedef struct PointAttributeSet {
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PointAttributeSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PointAttributeSet;

#ifdef __cplusplus
}
#endif

#endif	/* _PointAttributeSet_H_ */
#include <asn_internal.h>
