/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "C-ITS.ASN"
 */

#ifndef	_RoadPoint_H_
#define	_RoadPoint_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PositionOffsetLLV.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PointAttributeSet;
struct SegmentAttributeSet;

/* RoadPoint */
typedef struct RoadPoint {
	PositionOffsetLLV_t	 posOffset;
	struct PointAttributeSet	*pointAttribute	/* OPTIONAL */;
	struct SegmentAttributeSet	*segmentAttribute	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadPoint;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PointAttributeSet.h"
#include "SegmentAttributeSet.h"

#endif	/* _RoadPoint_H_ */
#include <asn_internal.h>
