/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "C-ITS.ASN"
 */

#ifndef	_SegmentAttributeSet_H_
#define	_SegmentAttributeSet_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SegmentAttributeSet */
typedef struct SegmentAttributeSet {
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SegmentAttributeSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SegmentAttributeSet;

#ifdef __cplusplus
}
#endif

#endif	/* _SegmentAttributeSet_H_ */
#include <asn_internal.h>
